services:
  tmms_realsense:
    image: tmms_image:0.1.2-amd64
    container_name: tmms_realsense
    entrypoint: ["/home/htxgrrt/.htxgrrt/bin/tmms_ws/tmms_ws_entrypoint.sh"]
    # Enable all port forwarding
    network_mode: "host"
    # Allow USB, LIDAR, or other devices access
    privileged: true
    # Interactive terminal for debugging
    stdin_open: true
    tty: true
    devices:
      - /dev:/dev
    volumes:
      # Required
      - /etc/localtime:/etc/localtime:ro                              # timezone binding
      - /etc/timezone:/etc/timezone:ro                                # timezone binding
      - /home/unitree/.htxgrrt/logs:/home/htxgrrt/.htxgrrt/logs               # logs binding
      - /home/unitree/.htxgrrt/etc:/home/htxgrrt/.htxgrrt/etc                 # etc binding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/unitree/.htxgrrt/bin/tmms_realsense/tmms_realsense_entrypoint.sh:/home/htxgrrt/.htxgrrt/bin/tmms_ws/tmms_ws_entrypoint.sh
      - /home/unitree/.htxgrrt/bin/tmms_realsense/custom.env:/home/htxgrrt/.htxgrrt/bin/tmms_ws/custom.env
      - /home/unitree/.htxgrrt/bin/tmms_realsense/cyclonedds.xml:/home/htxgrrt/.htxgrrt/bin/tmms_ws/cyclonedds.xml