[supervisord]
environment=HOME=/home/unitree

[program:tmms_realsense]
command=/bin/bash -c  "source /home/unitree/.bashrc && docker compose -f /home/unitree/.htxgrrt/bin/tmms_realsense/tmms_realsense-compose.yaml up"
autostart=true
autorestart=false
stopasgroup=true
killasgroup=true
stopsignal=SIGTERM
stopwaitsecs=15
user=unitree
redirect_stderr=true
stdout_logfile=/home/unitree/.htxgrrt/logs/tmms_realsense.log

[group:quadruped]
programs=tmms_realsense