services:
  tmms_run:
    image: tmms_image:0.1.1
    container_name: tmms_run
    entrypoint: ["/home/htxgrrt/.htxgrrt/bin/tmms_ws/tmms_ws_entrypoint.sh"]
    # Enable all port forwarding
    network_mode: "host"
    # Allow USB, LIDAR, or other devices access
    privileged: true
    # Interactive terminal for debugging
    stdin_open: true
    tty: true
    devices:
      - /dev:/dev
    volumes:
      # Required
      - /etc/localtime:/etc/localtime:ro                              # timezone binding
      - /etc/timezone:/etc/timezone:ro                                # timezone binding
      - /home/unitree/.htxgrrt/logs:/home/htxgrrt/.htxgrrt/logs               # logs binding
      - /home/unitree/.htxgrrt/bags:/home/htxgrrt/.htxgrrt/bags               # rosbags binding
      - /home/unitree/.htxgrrt/certs:/home/htxgrrt/.htxgrrt/certs:ro          # certs binding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Optional: ~/tmms_ws/install folder binding for custom binary
      - /home/unitree/.htxgrrt/bin/tmms_ws/install:/home/htxgrrt/.htxgrrt/bin/tmms_ws/install
      # - /home/unitree/.htxgrrt/bin/tmms_ws/build:/home/htxgrrt/.htxgrrt/bin/tmms_ws/build
      # - /home/unitree/.htxgrrt/bin/tmms_ws/src:/home/htxgrrt/.htxgrrt/bin/tmms_ws/src
      - /home/unitree/.htxgrrt/bin/tmms_ws/tmms_ws_entrypoint.sh:/home/htxgrrt/.htxgrrt/bin/tmms_ws/tmms_ws_entrypoint.sh
      - /home/unitree/.htxgrrt/bin/tmms_ws/custom.env:/home/htxgrrt/.htxgrrt/bin/tmms_ws/custom.env
      - /home/unitree/.htxgrrt/bin/tmms_ws/cyclonedds.xml:/home/htxgrrt/.htxgrrt/bin/tmms_ws/cyclonedds.xml