[supervisord]
environment=HOME=/home/unitree

[program:tmms_ws]
command=/bin/bash -i -c  "source /home/unitree/.bashrc && docker compose -f /home/unitree/.htxgrrt/bin/tmms_ws/tmms_ws-compose.yaml up"
autostart=true
autorestart=false
user=unitree
redirect_stderr=true
stdout_logfile=/home/unitree/.htxgrrt/logs/tmms_ws.log

[program:tmms_ui]
command=/bin/bash -i -c  "source /home/unitree/.bashrc && docker compose -f /home/unitree/.htxgrrt/bin/tmms_ui/tmms_ui-compose.yaml up"
autostart=true
autorestart=true
user=unitree
redirect_stderr=true
stdout_logfile=/home/unitree/.htxgrrt/logs/tmms_ui.log

[program:tmms_cams]
command=/bin/bash -i -c  "source /home/unitree/.bashrc && python3 /home/unitree/surround-view-system-introduction/run_tmms.py"
directory=/home/unitree/surround-view-system-introduction
autostart=true
autorestart=true
user=unitree
redirect_stderr=true
stdout_logfile=/home/unitree/.htxgrrt/logs/tmms_cams.log

[program:tmms_lichtblick]
command=/bin/bash -i -c  "source /home/unitree/.bashrc && docker compose -f /home/unitree/.htxgrrt/bin/tmms_lichtblick/tmms_lichtblick-compose.yaml up"
autostart=true
autorestart=true
user=unitree
redirect_stderr=true
stdout_logfile=/home/unitree/.htxgrrt/logs/tmms_lichtblick.log

[group:quadruped]
programs=tmms_ws, tmms_ui, tmms_cams, tmms_lichtblick